format = """
[î‚¶](#5e81ac)\
$os[](bg:#5e81ac fg:#2e3440)\
[î‚°](bg:#81a1c1 fg:#5e81ac)\
$directory\
[î‚°](bg:#88c0d0 fg:#81a1c1)\
$git_branch$git_commit$git_state$git_metrics$git_status\
[î‚°](bg:#8fbcbb fg:#88c0d0)\
$package$c$cmake$cobol$daml$dart$deno$dotnet$elixir$elm$erlang$fennel$gleam\
$golang$guix_shell$haskell$haxe$helm$java$julia$kotlin$gradle$lua$nim$nodejs\
$ocaml$opa$perl$php$pulumi$purescript$python$quarto$raku$rlang$red$ruby$rust\
$scala$solidity$swift$terraform$typst$vlang$vagrant$zig\
[î‚°](bg:#d9dee9 fg:#8fbcbb)\
$cmd_duration\
[î‚°](fg:#d9dee9)\
$time\
$line_break\
$character
"""

# EXCLUDED $
# ==========
# to add later if I need them lmao
# localip, shlvl, singularity, kubernetes
# vcsh, fossil_branch, fossil_branch_metrics, hg_branch, pijul_channel, docker_context
# buf, nix_shell, conda, meson, spack
# memory_usage
# aws, gcloud, openstack, azure
# direnv, env_var, crytal, custom, sudo
# jobs, status, container, shell

scan_timeout = 50
command_timeout = 1000
palette = 'nord'

[palettes.nord]
nord0 = "#2E3440"  # used for background and area coloring
nord1 = "#3B4252"  # used for elevated, more prominent or focused UI elements
nord2 = "#434C5E"  # used to colorize the currently active text editor line as well as selection- and text highlighting
nord3 = "#4C566A"  # used for UI elements like indent- and wrap guide marker
nord4 = "#D8DEE9"  # used for UI elements like the text editor caret
nord5 = "#E5E9F0"  # used for more subtle/inconspicuous UI text elements
nord6 = "#ECEFF4"  # used for elevated UI text elements that require more visual attention
nord7 = "#8FBCBB"  # used for UI elements that should, next to the primary accent color nord8, stand out and get more visual attention
nord8 = "#88C0D0"  # used for primary UI elements with main usage purposes that require the most visual attention
nord9 = "#81A1C1"  # used for secondary UI elements that also require more visual attention than other elements
nord10 = "#5E81AC" # used for tertiary UI elements that require more visual attention than default elements
nord11 = "#BF616A" # used for UI elements that are rendering error states like linter markers and the highlighting of Git diff deletions
nord12 = "#D08770" # rarely used for UI elements, but it may indicate a more advanced or dangerous functionality
nord13 = "#EBCB8B" # used for UI elements that are rendering warning states like linter markers and the highlighting of Git diff modifications
nord14 = "#A3BE8C" # used for UI elements that are rendering success states and visualizations and the highlighting of Git diff additions
nord15 = "#B48EAD" # rarely used for UI elements, but it may indicate a more uncommon functionality

# GIT
# ===

[git_branch]
format = "[ $symbol$branch(:$remote_branch) ]($style)"
symbol = "ó°˜¬ "
style = "fg:#2e3440 bg:#88c0d0"

[git_commit]

[git_state]

[git_metrics]
added_style = 'bg:nord0 fg:nord14'
deleted_style = 'bg:nord0 fg:nord11'
format = '[+$added ]($added_style)[-$deleted ]($deleted_style)'
disabled = false

[git_status]
style = "fg:#2e3440 bg:#88c0d0"
format = '[[($all_status$ahead_behind )](fg:#2e3440 bg:#88c0d0)]($style)'

# LANGUAGES
# =========

[lua]
symbol = 'ó°¢± '
format = '[ $symbol($version )]($style)'
style = "fg:#2e3440 bg:#8fbcbb"

[python]
symbol = 'ó°Œ  '
format = "[ $symbol($version )]($style)"
style = "fg:#2e3440 bg:#8fbcbb"

# MISC
# ====

[hostname]
ssh_only = false
style = "fg:#2e3440 bg:#5e81ac"
format = "[$ssh_symbol$hostname ]($style)"
ssh_symbol = "î¬ "

[os]
style = "fg:#2e3440 bg:#5e81ac"
disabled = false

#[os.symbols]
#Arch = 'ïŒƒ '

# status
[status]
format = '[ $symbol ]($style)'
style = "bold"
symbol = '[ï‘§](fg:nord11)'
success_symbol = '[îª²](fg:nord14)'
not_executable_symbol = '[ğŸ›‡](fg:nord11)'
not_found_symbol = '[ó°‰](fg:nord11)'
sigint_symbol = '[î€Š](fg:nord13)'
signal_symbol = '[î€Š](fg:nord11)'
disabled = false

# OS symbols
[os.symbols]
Alpaquita = 'îª¢ '
Alpine = 'ïŒ€ '
Amazon = 'ï‰° '
Android = 'ï…» '
Arch = 'ïŒƒ '
Artix = 'ïŒŸ '
CentOS = 'ïŒ„ '
Debian = 'ïŒ† '
DragonFly = 'îŠ '
Emscripten = 'ïˆ… '
EndeavourOS = 'ï†— '
Fedora = 'ïŒŠ '
FreeBSD = 'ïŒŒ '
Garuda = 'ó°›“ '
Gentoo = 'ïŒ '
HardenedBSD = 'ó°Œ '
Illumos = 'ó°ˆ¸ '
Linux = 'ïŒš '
Mabox = 'î¬© '
Macos = 'ïŒ‚ '
Manjaro = 'ïŒ’ '
Mariner = 'ï‡ '
MidnightBSD = 'ï†† '
Mint = 'ïŒ '
NetBSD = 'ï€¤ '
NixOS = 'ïŒ“ '
OpenBSD = 'ó°ˆº '
openSUSE = 'ïŒ” '
OracleLinux = 'ó°Œ· '
Pop = 'ïŒª '
Raspbian = 'ïŒ• '
Redhat = 'ïŒ– '
RedHatEnterprise = 'ïŒ– '
Redox = 'ó°€˜ '
Solus = 'ó° ³ '
SUSE = 'ïŒ” '
Ubuntu = 'ïŒ› '
Unknown = 'ïˆ­ '
Windows = 'ó°² '

[shell]
disabled = false

[username]
show_always = true
format = '[$user]($style)'
style_user = "fg:#2e3440 bg:#5e81ac"

[directory]
truncation_length = 1
truncate_to_repo = true
truncation_symbol = ''
style = "fg:#2e3440 bg:#81a1c1"
read_only = "î©µ "
format = "[ ó°‰‹ $path ]($style)[$read_only]($read_only_style)"
read_only_style = "fg:#2e3440 bold bg:#81a1c1"

[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "
"Work" = "î¯Ÿ "

[sudo]
disabled = false
symbol = "ï“Ÿ "
style = "fg:#2e3440 bg:#d9dee9"
format = "[ $symbol]($style)"

[cmd_duration]
format = "[ ó°”š $duration ]($style)"
style = "fg:#2e3440 bg:#d9dee9"

[character]
success_symbol = "[ ó±©](bold green)"
error_symbol = "[ ó±©](bold red)"
vimcmd_symbol = "[ î˜« ó±©](bold green)"

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[ ïº $time ](fg:#a0a9cb bg:#1d2230)]($style)'
