[colors.primary]
background = '#131314'
foreground = '#e4e2e3'
 
[colors.cursor]
text = '#e4e2e3'
cursor = '#c7c6c7' 
 
[colors.vi_mode_cursor]
text = '#131314'
cursor = '#bcc8d3' 
 
[colors.search.matches]
foreground = '#464748' 
background = '#b7c9d9' 
 
[colors.search.focused_match]
foreground = '#464748' 
background = '#bcc8d3' 
 
[colors.footer_bar]
foreground = '#464748' 
background = '#e4e2e3' 
 
[colors.hints.start]
foreground = '#464748' 
background = '#c1c7ce' 
 
[colors.hints.end]
foreground = '#464748' 
background = '#c1c7ce' 
 
[colors.selection]
text = '#131314'
background = '#bcc8d3'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#bcc8d3' 
yellow = '#54606a' 
blue = '#bcc8d3' 
magenta = '#b7c9d9' 
cyan = '#c1c7ce' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 